#!/bin/sh
LANGUAGE_CODE="${1:-vi_VN}"
CHROMESCRIPT=/opt/google/chrome/google-chrome

# Modify or add the LANGUAGE environment variable in the Chrome startup script
sed -i "s|^export LANGUAGE=.*|export LANGUAGE=\"$LANGUAGE_CODE\"|" "$CHROMESCRIPT" || \
(grep -q "export LANGUAGE=" "$CHROMESCRIPT" || \
{ cp "$CHROMESCRIPT" "$CHROMESCRIPT.old" -f; sed -i "1 a export LANGUAGE=\"$LANGUAGE_CODE\"" "$CHROMESCRIPT"; })
