name: Release

# Controls when the workflow will run
on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release action

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create Release
        uses: aaronbarnaby/create-release-action@v1.0.0
        with:
          title: ${{ github.ref_name }}
          api_token: ${{ secrets.GITHUB_TOKEN }}
          release_tag: ${{ github.ref_name }}
          files: |
            fixchrome
            install.sh
