name: Release

# Controls when the workflow will run
on:
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
  
    name: Release action
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare artifacts
        run: |
          mkdir release-artifacts
          cp fixchrome release-artifacts/
          cp install.sh release-artifacts/
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # Tên của release sẽ được tự động sinh từ tên tag
          # Ví dụ: tag 'beta' sẽ có tên là 'Release beta'
          name: Release ${{ github.ref_name }}
          # Nội dung của release sẽ được tự động tạo từ các commit kể từ tag gần nhất
          generate_release_notes: true
          # Đường dẫn đến các file bạn muốn upload
          files: |
            release-artifacts/*
